/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  tenant_document: () => import("@/views/tenant/document/index.vue"),
  tenant_event: () => import("@/views/tenant/event/index.vue"),
  tenant_family: () => import("@/views/tenant/family/index.vue"),
  tenant_member: () => import("@/views/tenant/member/index.vue"),
  tenant_photo: () => import("@/views/tenant/photo/index.vue"),
  "tenant_select-family": () => import("@/views/tenant/select-family/index.vue"),
  tenant_settings: () => import("@/views/tenant/settings/index.vue"),
};
