/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'tenant',
    path: '/tenant',
    component: 'layout.base',
    meta: {
      title: 'tenant',
      i18nKey: 'route.tenant',
      icon: 'mdi:family-tree',
      order: 2
    },
    children: [
      {
        name: 'tenant_document',
        path: '/tenant/document/:familyId?',
        component: 'view.tenant_document',
        meta: {
          title: 'tenant_document',
          i18nKey: 'route.tenant_document',
          icon: 'mdi:file-document-multiple'
        }
      },
      {
        name: 'tenant_event',
        path: '/tenant/event/:familyId?',
        component: 'view.tenant_event',
        meta: {
          title: 'tenant_event',
          i18nKey: 'route.tenant_event',
          icon: 'mdi:calendar-account'
        }
      },
      {
        name: 'tenant_member',
        path: '/tenant/member/:familyId?',
        component: 'view.tenant_member',
        meta: {
          title: 'tenant_member',
          i18nKey: 'route.tenant_member',
          icon: 'mdi:account-group'
        }
      },
      {
        name: 'tenant_permission',
        path: '/tenant/permission/:familyId?',
        component: 'view.tenant_permission',
        meta: {
          title: 'tenant_permission',
          i18nKey: 'route.tenant_permission',
          icon: 'mdi:shield-account'
        }
      },
      {
        name: 'tenant_photo',
        path: '/tenant/photo/:familyId?',
        component: 'view.tenant_photo',
        meta: {
          title: 'tenant_photo',
          i18nKey: 'route.tenant_photo',
          icon: 'mdi:image-multiple'
        }
      },
      {
        name: 'tenant_settings',
        path: '/tenant/settings/:familyId?',
        component: 'view.tenant_settings',
        meta: {
          title: 'tenant_settings',
          i18nKey: 'route.tenant_settings',
          icon: 'mdi:cog-outline'
        }
      }
    ]
  }
];
