/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "app-center": () => import("@/views/app-center/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "mini-program_banner": () => import("@/views/mini-program/banner/index.vue"),
  "mini-program_content": () => import("@/views/mini-program/content/index.vue"),
  "mini-program_family-invitation": () => import("@/views/mini-program/family-invitation/index.vue"),
  "mini-program_family-tree": () => import("@/views/mini-program/family-tree/index.vue"),
  "mini-program_family": () => import("@/views/mini-program/family/index.vue"),
  "mini-program_gathering": () => import("@/views/mini-program/gathering/index.vue"),
  "mini-program_generation-table": () => import("@/views/mini-program/generation-table/index.vue"),
  "mini-program_member": () => import("@/views/mini-program/member/index.vue"),
  "mini-program_members": () => import("@/views/mini-program/members/index.vue"),
  "mini-program_overview": () => import("@/views/mini-program/overview/index.vue"),
  "mini-program_subscription": () => import("@/views/mini-program/subscription/index.vue"),
  "mini-program_surname": () => import("@/views/mini-program/surname/index.vue"),
  "mini-program_worship": () => import("@/views/mini-program/worship/index.vue"),
  system_admin: () => import("@/views/system/admin/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_permission: () => import("@/views/system/permission/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_settings: () => import("@/views/system/settings/index.vue"),
  tenant: () => import("@/views/tenant/index.vue"),
};
