/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'app-center',
    path: '/app-center',
    component: 'layout.base$view.app-center',
    meta: {
      title: 'app-center',
      i18nKey: 'route.app-center',
      icon: 'mdi:puzzle',
      order: 4
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'mini-program',
    path: '/mini-program',
    component: 'layout.base',
    meta: {
      title: 'mini-program',
      i18nKey: 'route.mini-program'
    },
    children: [
      {
        name: 'mini-program_banner',
        path: '/mini-program/banner',
        component: 'view.mini-program_banner',
        meta: {
          title: 'mini-program_banner',
          i18nKey: 'route.mini-program_banner'
        }
      },
      {
        name: 'mini-program_content',
        path: '/mini-program/content',
        component: 'view.mini-program_content',
        meta: {
          title: 'mini-program_content',
          i18nKey: 'route.mini-program_content'
        }
      },
      {
        name: 'mini-program_family',
        path: '/mini-program/family',
        component: 'view.mini-program_family',
        meta: {
          title: 'mini-program_family',
          i18nKey: 'route.mini-program_family'
        }
      },
      {
        name: 'mini-program_family-invitation',
        path: '/mini-program/family-invitation',
        component: 'view.mini-program_family-invitation',
        meta: {
          title: 'mini-program_family-invitation',
          i18nKey: 'route.mini-program_family-invitation'
        }
      },
      {
        name: 'mini-program_family-tree',
        path: '/mini-program/family-tree',
        component: 'view.mini-program_family-tree',
        meta: {
          title: 'mini-program_family-tree',
          i18nKey: 'route.mini-program_family-tree'
        }
      },
      {
        name: 'mini-program_gathering',
        path: '/mini-program/gathering',
        component: 'view.mini-program_gathering',
        meta: {
          title: 'mini-program_gathering',
          i18nKey: 'route.mini-program_gathering'
        }
      },
      {
        name: 'mini-program_genealogy-book',
        path: '/mini-program/genealogy-book',
        component: 'view.mini-program_genealogy-book',
        meta: {
          title: 'mini-program_genealogy-book',
          i18nKey: 'route.mini-program_genealogy-book'
        }
      },
      {
        name: 'mini-program_generation-table',
        path: '/mini-program/generation-table',
        component: 'view.mini-program_generation-table',
        meta: {
          title: 'mini-program_generation-table',
          i18nKey: 'route.mini-program_generation-table'
        }
      },
      {
        name: 'mini-program_member',
        path: '/mini-program/member',
        component: 'view.mini-program_member',
        meta: {
          title: 'mini-program_member',
          i18nKey: 'route.mini-program_member'
        }
      },
      {
        name: 'mini-program_members',
        path: '/mini-program/members',
        component: 'view.mini-program_members',
        meta: {
          title: 'mini-program_members',
          i18nKey: 'route.mini-program_members'
        }
      },
      {
        name: 'mini-program_overview',
        path: '/mini-program/overview',
        component: 'view.mini-program_overview',
        meta: {
          title: 'mini-program_overview',
          i18nKey: 'route.mini-program_overview',
          hideInMenu: true
        }
      },
      {
        name: 'mini-program_subscription',
        path: '/mini-program/subscription',
        component: 'view.mini-program_subscription',
        meta: {
          title: 'mini-program_subscription',
          i18nKey: 'route.mini-program_subscription'
        }
      },
      {
        name: 'mini-program_surname',
        path: '/mini-program/surname',
        component: 'view.mini-program_surname',
        meta: {
          title: 'mini-program_surname',
          i18nKey: 'route.mini-program_surname'
        }
      },
      {
        name: 'mini-program_worship',
        path: '/mini-program/worship',
        component: 'view.mini-program_worship',
        meta: {
          title: 'mini-program_worship',
          i18nKey: 'route.mini-program_worship'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 3
    },
    children: [
      {
        name: 'system_admin',
        path: '/system/admin',
        component: 'view.system_admin',
        meta: {
          title: 'system_admin',
          i18nKey: 'route.system_admin'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_permission',
        path: '/system/permission',
        component: 'view.system_permission',
        meta: {
          title: 'system_permission',
          i18nKey: 'route.system_permission'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_settings',
        path: '/system/settings',
        component: 'view.system_settings',
        meta: {
          title: 'system_settings',
          i18nKey: 'route.system_settings'
        }
      }
    ]
  }
];
